import 'package:flutter/material.dart';

final List<Map<String, dynamic>> colorThemeTypes = [
  {'color': Colors.lime, 'label': '鲜绿'},
  {'color': Colors.lightGreen, 'label': '浅绿'},
  {'color': const Color(0xFF91AE84), 'label': '豆绿'},
  {'color': Colors.green, 'label': '松绿'},
  {'color': Colors.teal, 'label': '湖绿'},
  {'color': Colors.blueGrey[400], 'label': '灰蓝'},
  {'color': Colors.cyan, 'label': '青蓝'},
  {'color': Colors.lightBlue, 'label': '天蓝'},
  {'color': Colors.blue, 'label': '亮蓝'},
  {'color': const Color(0xFF191970), 'label': '深蓝'},
  {'color': Colors.indigo, 'label': '靛蓝'},
  {'color': Colors.deepPurple, 'label': '深紫'},
  {'color': Colors.purple, 'label': '魏紫'},
  {'color': const Color(0xFF8C4356), 'label': '绛紫'},
  {'color': const Color(0xFFB5001D), 'label': '大红'},
  {'color': Colors.pink, 'label': '枚红'},
  {'color': const Color(0xFFED5736), 'label': '妃红'},
  {'color': const Color(0xFFFB7299), 'label': '粉红'},
  {'color': Colors.red, 'label': '桃红'},
  {'color': Colors.deepOrange, 'label': '橙红'},
  {'color': const Color(0xFF993300), 'label': '棕红'},
  {'color': Colors.brown, 'label': '棕褐'},
  {'color': Colors.orange, 'label': '鲜橙'},
  {'color': Colors.amber, 'label': '橙黄'},
  {'color': Colors.yellow, 'label': '明黄'},
];
